name: Package Tools

# Controls when the action will run
on:
   # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  # Triggers the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Renamed job to "Build Package"
  BuildPackage:
    runs-on: ubuntu-latest
    # Set the MAJOR_VERSION environment variable
    env:
      MAJOR_VERSION: 0
    defaults:
      run:
        shell: bash
    steps:
      # Check out the repository's code
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      # Find all files with the .meta extension and save the list to a file
      - run: |
          find . -name \*.meta >> metaList
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
         filename: 'Packages/nl.brandonvdongen.pfctoolkit/package.json'
         prefix: packageMeta
         masked: true
      # Create a package directory
      - run: mkdir package

      # Use the create-unitypackage action to create a unity package from the .meta file list
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'package/PFCToolkit.unitypackage'
          include-files: metaList
      # copy the unity package file with the version number
      - name: Version release file
        run: cp "package/PFCToolkit.unitypackage" "package/PFCToolkit-v${{ env.packageMeta_version }}.unitypackage"
        # Rename the unity package to latest
      - name: Version release file
        run: mv "package/PFCToolkit.unitypackage" "package/Latest.unitypackage"
      # Use the automatic-releases action to create a new release and upload the unity package as an asset
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "v${{ env.packageMeta_version }}"
          prerelease: false
          title: "v${{ env.packageMeta_version }} Release"
          files: |
              package/PFCToolkit-v${{ env.packageMeta_version }}.unitypackage
      # Use the automatic-releases action to create a new release and upload the unity package as an asset
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Latest Release"
          files: |
              package/Latest.unitypackage
      # Echo the list of files in the package directory
      - name: Echo files
        run: ls package/
      - name: Discord notification
        uses: brandonvdongen/github-to-discord@main
        env:
         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         MESSAGE_TITLE: "Version v${{ env.packageMeta_version }} of PFCToolkit released!"
         MESSAGE_DESCRIPTION: "Update from the menu in the editor or download it from the release page on github!"
         MESSAGE_URL: https://github.com/brandonvdongen/PFCToolkit
         MESSAGE_COLOR: 5814783
